# Generated by Django 4.1.2 on 2022-11-29 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_1', models.CharField(max_length=30)),
                ('extra_2', models.CharField(max_length=30)),
                ('extra_3', models.CharField(max_length=30)),
                ('extra_4', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('used_car', 'Used_Car'), ('new_car', 'New_Car')], default='used_car', max_length=255)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_1', models.CharField(max_length=255)),
                ('desc_2', models.CharField(max_length=255)),
                ('desc_3', models.CharField(max_length=255)),
                ('desc_4', models.CharField(max_length=255)),
                ('desc_5', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_image', models.ImageField(default='race.jpg', upload_to='motors')),
                ('make', models.CharField(choices=[('Aston', 'Aston Martin'), ('Audi', 'Audi'), ('Gmc', 'Gmc'), ('Bentley', 'Bentley'), ('Bmw', 'Bmw'), ('Chevrolet', 'Chevrolet'), ('Cardilac', 'Cardilac'), ('Citroen', 'Citroen'), ('Hyundai', 'Hyundai'), ('Jaguar', 'Jaguar'), ('Lexus', 'Lexus'), ('Mercedes', 'Mercedes'), ('Nissan', 'Nissan')], max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('model_type', models.CharField(choices=[('Envoy', 'Envoy'), ('Jimmy', 'Jimmy'), ('Saturn', 'Saturn'), ('Savanna', 'Savanna'), ('Sierra', 'Siera'), ('Yukom', 'Sonoma')], max_length=255)),
                ('release_year', models.DateField(null=True)),
                ('fuel', models.CharField(max_length=255)),
                ('engine_mode_size', models.CharField(max_length=255)),
                ('power', models.CharField(max_length=255)),
                ('gearbox', models.CharField(max_length=255)),
                ('number_of_seats', models.IntegerField()),
                ('doors', models.IntegerField()),
                ('color', models.CharField(max_length=255)),
                ('slug', models.SlugField(null=True)),
                ('car_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_fleet.category')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_fleet.contact')),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('description', models.ManyToManyField(to='car_fleet.description')),
                ('extra', models.ManyToManyField(to='car_fleet.carextra')),
            ],
            options={
                'ordering': ['-make'],
            },
        ),
    ]
