# Generated by Django 4.1.2 on 2022-10-25 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_fleet', '0003_alter_car_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='image',
            new_name='car_image',
        ),
    ]
