# Generated by Django 4.1.2 on 2022-10-25 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_fleet', '0004_rename_image_car_car_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Extras',
            new_name='Extra',
        ),
    ]
