# Generated by Django 4.1.2 on 2022-10-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_fleet', '0006_alter_car_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=models.ImageField(default='race.jpg', upload_to='motors'),
        ),
    ]
