# Generated by Django 4.1.2 on 2023-01-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_fleet', '0007_alter_contact_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='avatar',
            field=models.ImageField(null=True, upload_to='media/profiles'),
        ),
    ]
