# Generated by Django 4.1 on 2022-10-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_fleet', '0008_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('used_car', 'Used_Car'), ('new_car', 'New_Car')], max_length=255),
        ),
    ]
