# Generated by Django 4.1.2 on 2022-11-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_fleet', '0009_delete_category_alter_car_car_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-make']},
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.CharField(default=300000, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('used_car', 'Used_Car'), ('new_car', 'New_Car')], default='Used_car', max_length=255),
        ),
    ]
