# Generated by Django 4.1 on 2022-11-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_fleet', '0010_alter_car_options_car_price_alter_car_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(choices=[('Aston', 'Aston Martin'), ('Audi', 'Audi'), ('Gmc', 'Gmc'), ('Bentley', 'Bentley'), ('Bmw', 'Bmw'), ('Chevrolet', 'Chevrolet'), ('Cardilac', 'Cardilac'), ('Citroen', 'Citroen'), ('Hyundai', 'Hyundai'), ('Jaguar', 'Jaguar'), ('Lexus', 'Lexus'), ('Mercedes', 'Mercedes'), ('Nissan', 'Nissan')], max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='model_type',
            field=models.CharField(choices=[('Envoy', 'Envoy'), ('Jimmy', 'Jimmy'), ('Saturn', 'Saturn'), ('Savanna', 'Savanna'), ('Sierra', 'Siera'), ('Yukom', 'Sonoma')], max_length=255),
        ),
    ]
