# Generated by Django 4.1 on 2022-11-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_fleet', '0012_alter_car_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicledescription',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.ManyToManyField(to='car_fleet.car'),
        ),
    ]
