# Generated by Django 4.1 on 2022-11-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_fleet', '0013_remove_vehicledescription_car_car_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
        migrations.RemoveField(
            model_name='extra',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='extra',
            field=models.ManyToManyField(to='car_fleet.extra'),
        ),
    ]
