# Generated by Django 4.1 on 2022-11-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_fleet', '0014_remove_car_description_remove_extra_car_car_extra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Extra',
            new_name='CarExtra',
        ),
        migrations.RenameModel(
            old_name='VehicleDescription',
            new_name='Description',
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.ManyToManyField(to='car_fleet.description'),
        ),
    ]
