# Generated by Django 4.1 on 2022-11-11 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_fleet', '0015_rename_extra_carextra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('used_car', 'Used_Car'), ('new_car', 'New_Car')], default='used_car', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_type',
        ),
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='car_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_fleet.category'),
        ),
    ]
