# Generated by Django 4.1.2 on 2022-11-29 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_fleet', '0018_alter_category_options_rename_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AddField(
            model_name='car',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_fleet.contact'),
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
